services:
  db:
    image: postgres:16-alpine
    container_name: cartlabs-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: cartlabs
      POSTGRES_USER: cartlabs
      POSTGRES_PASSWORD: cartlabs_password
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    image: soham170905/cartlabs-backend:latest 
    container_name: cartlabs-backend
    restart: unless-stopped
    environment:
      DATABASE_URL: postgresql+asyncpg://cartlabs:cartlabs_password@db:5432/cartlabs
      JWT_SECRET_KEY: change-this-secret-in-production
    expose:
      - "8000"
    depends_on:
      - db

  frontend:
    image: soham170905/cartlabs-frontend:latest
    container_name: cartlabs-frontend
    restart: unless-stopped
    expose:
      - "80"

  nginx:
    image: nginx:alpine
    container_name: cartlabs-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
      - backend

volumes:
  postgres_data: