events {}

http {
    server {
        listen 80;

        # Frontend
        location / {
            proxy_pass http://frontend:80;
        }

        # Backend API
        location /api/ {
            proxy_pass http://backend:8000/;
        }

        # 🔥 ADD THIS
        location /metrics {
            proxy_pass http://backend:8000/metrics;
        }
    }
}
